# Site settings
title: clojure dose
email: tir.karthi@gmail.com
description:
   A daily dose of clojure snippets from Clojurians
baseurl: ""
url: "http://tirkarthi.github.io/clojure-dose"
twitter_username: tirkarthi
github_username: tirkarthi

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

gems:
  - jekyll-feed
  - jemoji
